
name: countervision
dependencies:
  - python=3.7.*
  - numpy=1.18.*
  - scipy=1.4.*
  - scikit-learn=0.22.*
  - matplotlib=3.1.*
  - ipykernel
  - pandas=1.0.*
  - opencv=3.4.*
  - tqdm=4.46.*
  - nltk=3.5.*
